# Generated by Django 5.0.6 on 2024-07-08 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('idCurso', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Estudiantes',
            fields=[
                ('idEstudiantes', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Grado',
            fields=[
                ('idGrado', models.AutoField(primary_key=True, serialize=False)),
                ('grado', models.CharField(max_length=10)),
                ('aula', models.CharField(max_length=10)),
                ('seccion', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('idUsuarios', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('apellido', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=100)),
                ('direccion', models.CharField(blank=True, max_length=100, null=True)),
                ('password', models.CharField(max_length=100)),
                ('nombre_usuario', models.CharField(max_length=45, unique=True)),
                ('tipo_usuario', models.CharField(max_length=45)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('celular', models.CharField(blank=True, max_length=15, null=True)),
                ('dni', models.CharField(max_length=8, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Competencias',
            fields=[
                ('idCompetencias', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('idCurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competencias', to='login.curso')),
            ],
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('idasistencia', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('estado', models.CharField(choices=[('P', 'Presente'), ('T', 'Tardanza'), ('F', 'Falta'), ('J', 'Justificado')], max_length=1)),
                ('idCurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='login.curso')),
                ('idstudent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='login.estudiantes')),
            ],
        ),
        migrations.AddField(
            model_name='estudiantes',
            name='grado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estudiantes', to='login.grado'),
        ),
        migrations.CreateModel(
            name='MensajesJustificacion',
            fields=[
                ('idmensajes_justificacion', models.AutoField(primary_key=True, serialize=False)),
                ('mensaje', models.TextField()),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('idAsistencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_justificacion', to='login.asistencia')),
            ],
        ),
        migrations.CreateModel(
            name='Notas',
            fields=[
                ('idNotas', models.AutoField(primary_key=True, serialize=False)),
                ('nota', models.CharField(choices=[('C', 'C'), ('B', 'B'), ('A', 'A'), ('AD', 'AD')], max_length=2)),
                ('idCompetencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='login.competencias')),
                ('idStudent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='login.estudiantes')),
            ],
        ),
        migrations.CreateModel(
            name='Profesores',
            fields=[
                ('idProfesores', models.AutoField(primary_key=True, serialize=False)),
                ('especialidad', models.CharField(max_length=50, null=True)),
                ('img', models.ImageField(default='media/perfil.jpg', upload_to='media/fotosPerfil')),
                ('grado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profesores', to='login.grado')),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profesores', to='login.usuarios')),
            ],
        ),
        migrations.AddField(
            model_name='estudiantes',
            name='idUsuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudiantes', to='login.usuarios'),
        ),
        migrations.CreateModel(
            name='Administradores',
            fields=[
                ('idAdministradores', models.AutoField(primary_key=True, serialize=False)),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administradores', to='login.usuarios')),
            ],
        ),
    ]
