# Generated by Django 5.0.6 on 2024-07-08 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='nombre_usuario',
        ),
    ]
