# Generated by Django 5.0.6 on 2024-07-08 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_rename_administradores_administradore_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='apoderado',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
