# Generated by Django 5.0.6 on 2024-07-08 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_estudiante_apoderado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='hora_fin',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='hora_inicio',
        ),
    ]
