# Generated by Django 5.0.6 on 2024-07-10 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_alter_competencia_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asistencia',
            name='idCurso',
        ),
    ]
